sudo: false
dist: precise
language: node_js
node_js:
- '8'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_9a81afebf84f_key -iv $encrypted_9a81afebf84f_iv
  -in deploy.key.enc -out .travis/deploy.key -d
