sudo: false
dist: trusty
language: node_js
node_js:
- '8'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  chrome: stable
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - # start your web application and listen on `localhost`
  - export CHROME_BIN=google-chrome-stable
  - # google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - openssl aes-256-cbc -K $encrypted_9a81afebf84f_key -iv $encrypted_9a81afebf84f_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy.key # this key should have push access
  - ssh-add .travis/deploy.key
  - ssh-keyscan dokku.abarbanell.de >> ~/.ssh/known_hosts
  - git remote add deploy dokku@dokku.abarbanell.de:lg
  - git config --global push.default simple
  - git push deploy master

