sudo: false
dist: precise
language: node_js
node_js:
- '8'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_9a81afebf84f_key -iv $encrypted_9a81afebf84f_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.key # this key should have push access
  - ssh-add .travis/deploy_key.key
  - ssh-keyscan dokku.abarbanell.de >> ~/.ssh/known_hosts
  - git remote add deploy dokku@dokku.abarbanell.de:lg
  - git config --global push.default simple
  - git push deploy
